### ISSUE TITLE
Add incremental (potentially) checkpoints for long processing steps for fast recovery

### ISSUE THREAD

**Issue by guybartal** [microsoft/rag-experiment-accelerator#316]
Each main step of the pipeline comprised of several steps which can fail.
As a user I would like to be able to resume where it last failed.

**Comment by yuvalyaron** [comment]
# Design Draft

## Abstract
This draft suggests a general guideline on how this is planned to be implemented, some details are subject to change, based on feedback and implementation limitations.

## Design
We will introduce a Checkpoint object that will handle saving and loading data.  The Checkpoint object will be used to recover and continue the execution of previous executions.

There are 3 types of checkpoints:
1. LocalStroageCheckpoint - for persisting checkpoint data for local runs
3. AzureMLCheckpoint -  for persisting checkpoint data for Azure ML
4. NullCheckpoint - a dummy implementation that does not do anything, will be used in cases the checkpoints should be ignored.

The Checkpoint interface will have 3 methods:
1. **exists**- to test whether a checkpoint already exists - and thus should be used instead of doing work that was already been done.
2. **load** - to load checkpoint data
3. **save** - to save checkpoint data

Here is a pseudo usage of the checkpoint object for the `indexing` step which is very close the the actual implementation:
```
if checkpoint.exists():
    documents = checkpoint.load()
else:
    documents = load_documents(...)
    checkpoint.save(documents)

embed_chunks(..., documents)
checkpoint.save(documents)

generate_titles_from_chunks(..., documents)
checkpoint.save(documents)

generate_summaries_from_chunks(..., documents)
checkpoint.save(documents)
```

### LocalStroageCheckpoint 
Will use the [pickle ](https://docs.python.org/3/library/pickle.html) library for serializing the objects that should be saved.
The serialized object will be persisted to memory on `save`, and deserialized on `load`.

### NullCheckpoint 
All methods implementation will be `pass`, and will do nothing when called.
This is for cases when we want to turn off the checkpointing, either if the user opted out, or if the flow requires to skip it.

### AzureMLCheckpoint 

The main idea here is that when each machine (compute instance) starts, data from previous executions will be downloaded into the machine and be unified into a single checkpoint.

This implementation will have 2 additional methods.
`mount` that will be called at the startup, and `unmount` that will be called when the pipeline finishes.

1. **unmount** - in this step, each compute instance will upload its checkpoint data to the shared storage. The shared storage will contain the data of all the checkpoints and is copied to each machine in the mount step.

![image](https://github.com/microsoft/rag-experiment-accelerator/assets/43217306/dc28a9fb-0f73-47c0-9467-c9b5df55adae)

2. **mount**-  will be invoked at the startup of the pipeline. In this step, we will download the data from the previous execution into the ephemeral storage of the compute instance. The `checkpoint.load()` will return a list, where each element is the content of a checkpoint file and then it will be combined.

![image](https://github.com/microsoft/rag-experiment-accelerator/assets/43217306/8381b7d1-b8a8-4883-8ec3-d096ae3b4e9d)

Then, each compute instance will have the unified single checkpoint:
![image](https://github.com/microsoft/rag-experiment-accelerator/assets/43217306/a9f5e33a-9466-473f-959a-565457f56fae)

**Comment by yuvalyaron** [comment]
closing as it's a duplication of #186
